//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astaberry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class TblCart
    {
        [Key]
        public int Cartid { get; set; }
        [Required]
        public string Emailid { get; set; }
        [Required]
        public string Skucode { get; set; }
        [Required]
        public int Qty { get; set; }
        [Required]
        public string ParentId { get; set; }

        [Required]
        public string Image { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public double Price { get; set; }
        [Required]
        public double? Gst { get; set; }
    
    }
}
