//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astaberry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class TblCouponCode
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Couponcode { get; set; }
        [Required]
        public double Discount { get; set; }
        [Required]
        public int Maxallowed { get; set; }
        [Required]
        public string ApplicableFor { get; set; }
        public string Applicableon { get; set; }
    }
}
