//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astaberry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class TblProductDesc
    {
        public int Id { get; set; }
        [Required]
        public string Skucode { get; set; }
        [Required]
        public string ProductName { get; set; }
        [Required]
        public int Categoryid { get; set; }
        [Required]
        public int Subcategoryid { get; set; }
        [Required]
        public int BrandId { get; set; }
        [Required]
        public string ShortDesc { get; set; }
        [Required]
        public string LongDesc { get; set; }
        
        [Required]
        public int SkinType { get; set; }
        [Required]
        public string Metakeyword { get; set; }

        [Required]
        public string MetaDescription { get; set; } 
        
        [Required]
        public double Gst { get; set; }

       
        public string CustomeUrl { get; set; }

        
        public int Range { get; set; }

        [Required]
        public string GroupName { get; set; }


    }
}
