//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astaberry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class TblPaymentHistory
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string OrderId { get; set; }
        [Required]
        public double AmountRecieved { get; set; }
        [Required]
        public string Date { get; set; }
    }
}
